language: generic

sudo: required

services:
  - docker

install:
  - docker pull archlinux/base:latest

script:
  - docker build . -t $DOCKER_USER/joypixels-fonts-build
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $DOCKER_USER/joypixels-fonts-build

env:
  global:
    - secure: "B7S3O5Z6R+jOkHKe6JP9Y9JjR8xoJ0Xvin2etBAJQCQq8+4CLMQCGMyN4rL1JLNVT5tqtIzm302l03Cc8H5d3stY13VCotcz0sCCJz6P64+G3QgkOVrFx0ukb6kzj8GOV9T0SFmejx7LEYa/Ns3/CqYnqDVQPI3HVX4BgfTBbuOwBQ+Gu9iOZj2TpeFD13y2YBtFf7a4GDYdO7jddyLUQRQatBE8PFeumQf31dUmwFwzlJii9T/UDwHL/s8moIYqzszSj8EL9fv6JC8uiOVQbRoa0jrBYf8U0I5gGNiocZAMRhKnEBQx7B15tUbOV9IFfhHXvXlBAx7HoLOaxUwnmieiAvlLa7tFN8eQDDqC3MYOd3UrCnUH1SP7x4AGTRF1YUpVDLv1TiQuqUuRcIcL1H/5xhL/m07SBFeDUCiV6eXbhy4ghQ2PuS6dIlq4fl1bLUDvVM79RdCQ2cN6au3gDGncQr2vkMNwu/Ni6IEa5uvHOjMXi3evCLIj5FoUVH8D9jIXIH2L8XE9ZOTlHHajP9FdGF7cEenRXJtMrLap1tZMTs670BOrxFsW+gRb3w6fo33Gsgut+sXERHMKaQOEzk/SwKTnDE39BkYUeuk2ELUCjFkppRzDKjDVw8raFn2Nn0pfRXqnISIY+3SNFMbx7UQ8uQyNDc64yAhWVcGDqN4="
    - secure: "kb/VR81GiJVoO6EJU/qlyj/idGlLJIGg4e9bN60b1Raa11CPuTUZTikLKZSV+orId2Xyh+3bzo4aN2Vk1sxUpenc0LqGe16bIGNSxYb0QF0O6oMl349uhUTYok7X/MYKtl4zTpyy02wJvn3qZ4HyLa7qhMeprj7b0U/qCmgwxA2XlYAHgn7HZvzjZBYvsnUsDAcX95cwvpO5TqCW9d0HlxT7jq4e9APfN2VNYdOQp0yZlyEyHUoGiAVGoAPwA++8mLSjHbCcCk3uuV4QJrBLWww/OqsS1fyChcBOCtRhMYMrK1XMUDqv1uzbdbDVR3enIVuwPCK2wAsHiGA2yy4RV0MWVtMQgbjX1wSeG4BqOMAVyVmPvXcvZ2nGkE4XtlKON/FUq5h8zrOV0tiHSAMlG0YOwvbA1MsSQRCaDwZnz14281ldBdLANHR1TvxXPSzI2f03nhIa4cSF/Oa9559hV2EkGYvLRzKukzC4xXqL0Pyeky7pLXmW7iDAfpJYHkdFCe67S2vryL7rKxLruuWnLjolpfniWosC7Z8zNRwo7dZbSTXk57/WQTfbJO+d9EdBC06QTFwr0fzbVhFckjnCYciMYpt+aTW2CHI8/pAQZQEOGXro+mP8xtxLWq50WZ3sZarxSHbi6/pgHJ+/OQ9W+TgDQ8gcMkCh7NvfGqvZCB4="
